os: linux
dist: focal
language: python

branches:
  only:
    - master

before_script:
  - sudo wget https://dvc.org/deb/dvc.list -O /etc/apt/sources.list.d/dvc.list
  - sudo apt-get update
  - sudo apt-get install dvc
  - dvc pull

script:
  - dvc repro -f annotate_train

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_GITHUB_TOKEN
  keep_history: false
  local_dir: html
  verbose: true
  on:
    branch: master
