stages:
  parse_train:
    cmd: python3 -m purano.run_parse --inputs data/documents/ru_tg_0525.jsonl --fmt
      jsonl --output-file output/train_parsed.db --cleaner-config configs/cleaner.jsonnet
    deps:
    - data/documents/ru_tg_0525.jsonl
    - purano/run_parse.py
    params:
    - configs/cleaner.jsonnet:
      - cat_detect_model_path
      - is_lower
      - is_news_only
      - is_russian_only
      - lang_detect_model_path
    outs:
    - output/train_parsed.db
  annotate_train:
    cmd: python3 -m purano.run_annotate --config configs/annotator.jsonnet --reannotate
      --sort-by-date --output-file output/train_annotated.db --input-file output/train_parsed.db
    deps:
    - configs/annotator.jsonnet
    - output/train_parsed.db
    - purano/run_annotate.py
    outs:
    - output/train_annotated.db
  clustering_train:
    cmd: python3 -m purano.run_clustering --config configs/clusterer.jsonnet --sort-by-date
      --output-file output/clusters.json --input-file output/train_annotated.db
    deps:
    - output/train_annotated.db
    - purano/run_clustering.py
    - purano/clusterer/clusterer.py
    params:
    - configs/clusterer.jsonnet:
      - clustering_params.affinity
      - clustering_params.distance_threshold
      - clustering_params.linkage
      - clustering_params.n_clusters
      - clustering_type
      - embeddings.aggregation
      - embeddings.keys
      - embeddings.weights
      - entities_key
      - fix_hosts
      - hosts_penalty
      - fix_time
      - time_penalty
    outs:
    - output/clusters.json
  evaluate_train:
    cmd: python3 -m purano.run_evaluate --clustering-markup data/markup/ru_clustering_0525.tsv
      --original-json data/documents/ru_tg_0525.jsonl --threads-json output/clusters.json
      --output-json output/metrics.json
    deps:
    - data/documents/ru_tg_0525.jsonl
    - data/markup/ru_clustering_0525.tsv
    - output/clusters.json
    - purano/run_evaluate.py
    metrics:
    - output/metrics.json:
        cache: false
