stages:
  parse_0525:
    cmd: python3 -m purano.run_parse --inputs data/documents/ru_tg_0525.jsonl --fmt
      jsonl --output-file output/0525_parsed.db --cleaner-config configs/cleaner.jsonnet
    deps:
    - data/documents/ru_tg_0525.jsonl
    - purano/run_parse.py
    params:
    - configs/cleaner.jsonnet:
      - cat_detect_model_path
      - is_lower
      - is_news_only
      - is_russian_only
      - lang_detect_model_path
    outs:
    - output/0525_parsed.db
  annotate_0525:
    cmd: python3 -m purano.run_annotate --config configs/annotator.jsonnet --reannotate
      --sort-by-date --output-file output/0525_annotated.db --input-file output/0525_parsed.db
    deps:
    - configs/annotator.jsonnet
    - output/0525_parsed.db
    - purano/run_annotate.py
    - models/fasttext
    - models/slovnet
    - models/text2title/ru_ft_text_embedder.pt
    - models/text2title/ru_ft_title_embedder.pt
    - models/tfidf/ru_idfs.txt
    outs:
    - output/0525_annotated.db
  annotate_light_0525:
    cmd: python3 -m purano.run_annotate --config configs/annotator_light.jsonnet --reannotate
      --sort-by-date --output-file output/0525_annotated_light.db --input-file output/0525_parsed.db
    deps:
    - configs/annotator_light.jsonnet
    - output/0525_parsed.db
    - purano/run_annotate.py
    - models/fasttext
    - models/slovnet
    - models/text2title/ru_ft_text_embedder.pt
    - models/text2title/ru_ft_title_embedder.pt
    - models/tfidf/ru_idfs.txt
    outs:
    - output/0525_annotated_light.db
  clustering_0525:
    cmd: python3 -m purano.run_clustering --config configs/clusterer.jsonnet --sort-by-date
      --output-file output/0525_clusters.json --input-file output/0525_annotated.db
    deps:
    - output/0525_annotated.db
    - purano/run_clustering.py
    - purano/clusterer/clusterer.py
    params:
    - configs/clusterer.jsonnet:
      - clustering
      - fetching.embeddings.aggregation
      - fetching.embeddings.keys
      - fetching.embeddings.weights
      - fetching.entities_key
      - distances.fix_hosts
      - distances.hosts_penalty
      - distances.fix_time
      - distances.time_penalty
    outs:
    - output/0525_clusters.json
  evaluate_0525:
    cmd: python3 -m purano.run_evaluate --clustering-markup-tsv data/markup/ru_clustering_0525.tsv
      --original-json data/documents/ru_tg_0525.jsonl --threads-json output/0525_clusters.json
      --output-json output/0525_metrics.json
    deps:
    - data/documents/ru_tg_0525.jsonl
    - data/markup/ru_clustering_0525.tsv
    - output/0525_clusters.json
    - purano/clusterer/metrics.py
    - purano/run_evaluate.py
    metrics:
    - output/0525_metrics.json:
        cache: false
  training_tfidf_model:
    cmd: python3 -m purano.training.train_tfidf --config-file configs/training/tfidf.jsonnet
      --input-file data/documents/ru_tg_1101_0510.jsonl.tar.gz --output-file models/tfidf/ru_idfs.txt
      --svd-matrix-file models/tfidf/svd_matrix.pt
    deps:
    - data/documents/ru_tg_1101_0510.jsonl.tar.gz
    - purano/training/models/tfidf.py
    - purano/training/train_tfidf.py
    params:
    - configs/training/tfidf.jsonnet:
      - building.max_df
      - building.min_df
      - svd_dim
    outs:
    - models/tfidf/ru_idfs.txt
    - models/tfidf/svd_matrix.pt
  training_text2title_model:
    cmd: python3 -m purano.training.train_text2title --config-file configs/training/text2title.jsonnet
      --train-file data/documents/ru_tg_1101_0510.jsonl.tar.gz --val-file data/documents/ru_tg_0511_0517.jsonl
      --output-title-model-path models/text2title/ru_ft_title_embedder.pt --output-text-model-path
      models/text2title/ru_ft_text_embedder.pt --train-sample-rate 0.2 --val-sample-rate
      0.2 --neptune-project "ilya-gusev/purano"
    deps:
    - data/documents/ru_tg_0511_0517.jsonl
    - data/documents/ru_tg_1101_0510.jsonl.tar.gz
    - models/fasttext/ru_vectors_v3.bin
    - purano/training/datasets/text2title.py
    - purano/training/models/text2title.py
    - purano/training/train_text2title.py
    params:
    - configs/training/text2title.jsonnet:
      - batch_size
      - epochs
      - ft_vector_model_path
      - max_words
      - num_workers
      - patience
    outs:
    - models/text2title/ru_ft_text_embedder.pt
    - models/text2title/ru_ft_title_embedder.pt
