# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='info.proto',
  package='info',
  syntax='proto3',
  serialized_pb=_b('\n\ninfo.proto\x12\x04info\"A\n\x04Info\x12\x1c\n\x14title_bert_embedding\x18\x01 \x03(\x01\x12\x1b\n\x13text_bert_embedding\x18\x02 \x03(\x01\x62\x06proto3')
)




_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='info.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title_bert_embedding', full_name='info.Info.title_bert_embedding', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text_bert_embedding', full_name='info.Info.text_bert_embedding', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['Info'] = _INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), dict(
  DESCRIPTOR = _INFO,
  __module__ = 'info_pb2'
  # @@protoc_insertion_point(class_scope:info.Info)
  ))
_sym_db.RegisterMessage(Info)


# @@protoc_insertion_point(module_scope)
