# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='info.proto',
  package='info',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ninfo.proto\x12\x04info\"m\n\nEntitySpan\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\x04\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x04\x12!\n\x03tag\x18\x03 \x01(\x0e\x32\x14.info.EntitySpan.Tag\" \n\x03Tag\x12\x07\n\x03LOC\x10\x00\x12\x07\n\x03PER\x10\x01\x12\x07\n\x03ORG\x10\x02\"\x99\x04\n\x04Info\x12 \n\x18title_fasttext_embedding\x18\x01 \x03(\x01\x12\x1f\n\x17text_fasttext_embedding\x18\x02 \x03(\x01\x12%\n\x1dtitle_text_fasttext_embedding\x18\x03 \x03(\x01\x12\"\n\x1atitle_xlmroberta_embedding\x18\x04 \x03(\x01\x12\x1c\n\x14title_elmo_embedding\x18\x05 \x03(\x01\x12+\n\x11title_slovnet_ner\x18\x06 \x03(\x0b\x32\x10.info.EntitySpan\x12\'\n\x1ftitle_linear_fasttext_embedding\x18\x07 \x03(\x01\x12&\n\x1etext_linear_fasttext_embedding\x18\x08 \x03(\x01\x12\x16\n\x0etfidf_keywords\x18\t \x03(\t\x12\'\n\x1ftitle_text_xlmroberta_embedding\x18\n \x03(\x01\x12\x1b\n\x13gen_title_embedding\x18\x0b \x03(\x01\x12*\n\x10text_slovnet_ner\x18\x0c \x03(\x0b\x32\x10.info.EntitySpan\x12\x17\n\x0ftfidf_embedding\x18\r \x03(\x01\x12+\n#title_text_news_tg_rubert_embedding\x18\x0e \x03(\x01\x12\x17\n\x0flabse_embedding\x18\x0f \x03(\x01\x62\x06proto3'
)



_ENTITYSPAN_TAG = _descriptor.EnumDescriptor(
  name='Tag',
  full_name='info.EntitySpan.Tag',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOC', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ORG', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=97,
  serialized_end=129,
)
_sym_db.RegisterEnumDescriptor(_ENTITYSPAN_TAG)


_ENTITYSPAN = _descriptor.Descriptor(
  name='EntitySpan',
  full_name='info.EntitySpan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin', full_name='info.EntitySpan.begin', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='info.EntitySpan.end', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag', full_name='info.EntitySpan.tag', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENTITYSPAN_TAG,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=129,
)


_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='info.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title_fasttext_embedding', full_name='info.Info.title_fasttext_embedding', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_fasttext_embedding', full_name='info.Info.text_fasttext_embedding', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_text_fasttext_embedding', full_name='info.Info.title_text_fasttext_embedding', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_xlmroberta_embedding', full_name='info.Info.title_xlmroberta_embedding', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_elmo_embedding', full_name='info.Info.title_elmo_embedding', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_slovnet_ner', full_name='info.Info.title_slovnet_ner', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_linear_fasttext_embedding', full_name='info.Info.title_linear_fasttext_embedding', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_linear_fasttext_embedding', full_name='info.Info.text_linear_fasttext_embedding', index=7,
      number=8, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tfidf_keywords', full_name='info.Info.tfidf_keywords', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_text_xlmroberta_embedding', full_name='info.Info.title_text_xlmroberta_embedding', index=9,
      number=10, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gen_title_embedding', full_name='info.Info.gen_title_embedding', index=10,
      number=11, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_slovnet_ner', full_name='info.Info.text_slovnet_ner', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tfidf_embedding', full_name='info.Info.tfidf_embedding', index=12,
      number=13, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title_text_news_tg_rubert_embedding', full_name='info.Info.title_text_news_tg_rubert_embedding', index=13,
      number=14, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='labse_embedding', full_name='info.Info.labse_embedding', index=14,
      number=15, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=669,
)

_ENTITYSPAN.fields_by_name['tag'].enum_type = _ENTITYSPAN_TAG
_ENTITYSPAN_TAG.containing_type = _ENTITYSPAN
_INFO.fields_by_name['title_slovnet_ner'].message_type = _ENTITYSPAN
_INFO.fields_by_name['text_slovnet_ner'].message_type = _ENTITYSPAN
DESCRIPTOR.message_types_by_name['EntitySpan'] = _ENTITYSPAN
DESCRIPTOR.message_types_by_name['Info'] = _INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EntitySpan = _reflection.GeneratedProtocolMessageType('EntitySpan', (_message.Message,), {
  'DESCRIPTOR' : _ENTITYSPAN,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:info.EntitySpan)
  })
_sym_db.RegisterMessage(EntitySpan)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:info.Info)
  })
_sym_db.RegisterMessage(Info)


# @@protoc_insertion_point(module_scope)
